-- Note: This migration is for reference. Supabase email templates are configured via the dashboard
-- or using the Supabase CLI. The actual template configuration would be done through:
-- 1. Supabase Dashboard > Authentication > Email Templates
-- 2. Or using the Supabase CLI: supabase auth email-templates update

-- For now, we'll create a function to help with email template management
CREATE OR REPLACE FUNCTION get_email_template_config()
RETURNS JSON AS $$
BEGIN
    RETURN '{
        "confirm_signup": {
            "subject": "Welcome to Market-Mage! Confirm Your Account ✨",
            "content": {
                "html": "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>Welcome to Market-Mage</title><style>body{font-family:Arial,sans-serif;background:linear-gradient(135deg,#0f0f23 0%,#1a1a2e 50%,#16213e 100%);color:#fff;margin:0;padding:20px;} .container{max-width:600px;margin:0 auto;background:rgba(255,255,255,0.05);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,0.1);border-radius:15px;padding:40px;box-shadow:0 8px 32px rgba(0,0,0,0.3);} .header{text-align:center;margin-bottom:30px;} .logo{width:60px;height:60px;margin:0 auto 20px;border-radius:8px;box-shadow:0 4px 15px rgba(59,130,246,0.3);object-fit:cover;} .title{font-size:28px;font-weight:bold;color:#3b82f6;margin-bottom:10px;} .subtitle{color:#9ca3af;font-size:16px;} .content{margin:30px 0;} .button{display:inline-block;background:linear-gradient(135deg,#3b82f6,#1d4ed8);color:#fff;padding:15px 30px;text-decoration:none;border-radius:8px;font-weight:bold;margin:20px 0;box-shadow:0 4px 15px rgba(59,130,246,0.3);} .features{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:20px;margin:30px 0;} .feature{text-align:center;padding:15px;background:rgba(59,130,246,0.1);border-radius:8px;} .feature-icon{font-size:24px;margin-bottom:10px;} .footer{text-align:center;margin-top:30px;padding-top:20px;border-top:1px solid rgba(255,255,255,0.1);color:#9ca3af;font-size:14px;}</style></head><body><div class=\"container\"><div class=\"header\"><img src=\"https://market-mage.netlify.app/icon-1.png\" alt=\"Market-Mage\" class=\"logo\"><h1 class=\"title\">Welcome to Market-Mage!</h1><p class=\"subtitle\">Your AI-powered trading companion</p></div><div class=\"content\"><p>Hello {{ .Name }},</p><p>Welcome to Market-Mage! We\'re excited to have you join our community of smart traders.</p><p>To get started, please confirm your email address by clicking the button below:</p><div style=\"text-align:center;\"><a href=\"{{ .ConfirmationURL }}\" class=\"button\">✨ Confirm My Account</a></div><div class=\"features\"><div class=\"feature\"><div class=\"feature-icon\">📊</div><div>Smart Dashboards</div></div><div class=\"feature\"><div class=\"feature-icon\">🧠</div><div>AI Insights</div></div><div class=\"feature\"><div class=\"feature-icon\">⚡</div><div>Real-time Data</div></div></div><p>After confirming your account, you\'ll be able to:</p><ul><li>Create personalized trading dashboards</li><li>Get AI-powered market insights</li><li>Track crypto and stock portfolios</li><li>Access real-time market data</li></ul></div><div class=\"footer\"><p>If you didn\'t create this account, you can safely ignore this email.</p><p>© 2024 Market-Mage. Powered by AI Magic.</p></div></div></body></html>",
                "text": "Welcome to Market-Mage!\\n\\nHello {{ .Name }},\\n\\nWelcome to Market-Mage! We're excited to have you join our community of smart traders.\\n\\nTo get started, please confirm your email address by visiting:\\n{{ .ConfirmationURL }}\\n\\nAfter confirming your account, you'll be able to:\\n• Create personalized trading dashboards\\n• Get AI-powered market insights\\n• Track crypto and stock portfolios\\n• Access real-time market data\\n\\nIf you didn't create this account, you can safely ignore this email.\\n\\n© 2024 Market-Mage. Powered by AI Magic."
            }
        },
        "confirm_email_change": {
            "subject": "Confirm Your New Email Address - Market-Mage",
            "content": {
                "html": "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>Confirm Email Change</title><style>body{font-family:Arial,sans-serif;background:linear-gradient(135deg,#0f0f23 0%,#1a1a2e 50%,#16213e 100%);color:#fff;margin:0;padding:20px;} .container{max-width:600px;margin:0 auto;background:rgba(255,255,255,0.05);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,0.1);border-radius:15px;padding:40px;box-shadow:0 8px 32px rgba(0,0,0,0.3);} .header{text-align:center;margin-bottom:30px;} .logo{width:60px;height:60px;margin:0 auto 20px;border-radius:8px;box-shadow:0 4px 15px rgba(59,130,246,0.3);object-fit:cover;} .title{font-size:28px;font-weight:bold;color:#3b82f6;margin-bottom:10px;} .button{display:inline-block;background:linear-gradient(135deg,#3b82f6,#1d4ed8);color:#fff;padding:15px 30px;text-decoration:none;border-radius:8px;font-weight:bold;margin:20px 0;box-shadow:0 4px 15px rgba(59,130,246,0.3);} .footer{text-align:center;margin-top:30px;padding-top:20px;border-top:1px solid rgba(255,255,255,0.1);color:#9ca3af;font-size:14px;}</style></head><body><div class=\"container\"><div class=\"header\"><img src=\"https://market-mage.netlify.app/icon-1.png\" alt=\"Market-Mage\" class=\"logo\"><h1 class=\"title\">Confirm Email Change</h1></div><div class=\"content\"><p>Hello {{ .Name }},</p><p>You've requested to change your email address for your Market-Mage account.</p><p>To confirm this change, please click the button below:</p><div style=\"text-align:center;\"><a href=\"{{ .ConfirmationURL }}\" class=\"button\">✅ Confirm Email Change</a></div><p>If you didn't request this change, please contact our support team immediately.</p></div><div class=\"footer\"><p>© 2024 Market-Mage. Powered by AI Magic.</p></div></div></body></html>",
                "text": "Confirm Email Change - Market-Mage\\n\\nHello {{ .Name }},\\n\\nYou've requested to change your email address for your Market-Mage account.\\n\\nTo confirm this change, please visit:\\n{{ .ConfirmationURL }}\\n\\nIf you didn't request this change, please contact our support team immediately.\\n\\n© 2024 Market-Mage. Powered by AI Magic."
            }
        },
        "recovery": {
            "subject": "Reset Your Password - Market-Mage",
            "content": {
                "html": "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>Reset Password</title><style>body{font-family:Arial,sans-serif;background:linear-gradient(135deg,#0f0f23 0%,#1a1a2e 50%,#16213e 100%);color:#fff;margin:0;padding:20px;} .container{max-width:600px;margin:0 auto;background:rgba(255,255,255,0.05);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,0.1);border-radius:15px;padding:40px;box-shadow:0 8px 32px rgba(0,0,0,0.3);} .header{text-align:center;margin-bottom:30px;} .logo{width:60px;height:60px;margin:0 auto 20px;border-radius:8px;box-shadow:0 4px 15px rgba(59,130,246,0.3);object-fit:cover;} .title{font-size:28px;font-weight:bold;color:#3b82f6;margin-bottom:10px;} .button{display:inline-block;background:linear-gradient(135deg,#ef4444,#dc2626);color:#fff;padding:15px 30px;text-decoration:none;border-radius:8px;font-weight:bold;margin:20px 0;box-shadow:0 4px 15px rgba(239,68,68,0.3);} .footer{text-align:center;margin-top:30px;padding-top:20px;border-top:1px solid rgba(255,255,255,0.1);color:#9ca3af;font-size:14px;}</style></head><body><div class=\"container\"><div class=\"header\"><img src=\"https://market-mage.netlify.app/icon-1.png\" alt=\"Market-Mage\" class=\"logo\"><h1 class=\"title\">Reset Your Password</h1></div><div class=\"content\"><p>Hello {{ .Name }},</p><p>You've requested to reset your password for your Market-Mage account.</p><p>To reset your password, please click the button below:</p><div style=\"text-align:center;\"><a href=\"{{ .ConfirmationURL }}\" class=\"button\">🔐 Reset Password</a></div><p>This link will expire in 1 hour for security reasons.</p><p>If you didn't request this password reset, please ignore this email and your password will remain unchanged.</p></div><div class=\"footer\"><p>© 2024 Market-Mage. Powered by AI Magic.</p></div></div></body></html>",
                "text": "Reset Your Password - Market-Mage\\n\\nHello {{ .Name }},\\n\\nYou've requested to reset your password for your Market-Mage account.\\n\\nTo reset your password, please visit:\\n{{ .ConfirmationURL }}\\n\\nThis link will expire in 1 hour for security reasons.\\n\\nIf you didn't request this password reset, please ignore this email and your password will remain unchanged.\\n\\n© 2024 Market-Mage. Powered by AI Magic."
            }
        }
    }'::json;
END;
$$ LANGUAGE plpgsql; 